# Generated by Django 4.0 on 2022-01-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='food_type',
            field=models.CharField(choices=[('veg', 'VEG'), ('non-veg', 'NON-VEG'), ('drinks', 'DRINKS'), ('sweets', 'SWEETS')], default='veg', max_length=50),
            preserve_default=False,
        ),
    ]
