# Generated by Django 4.0 on 2022-01-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0004_menu_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
