# Generated by Django 4.0 on 2022-01-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0005_alter_menu_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item_name',
            field=models.CharField(max_length=50),
        ),
    ]
