# Generated by Django 4.0 on 2022-01-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0006_alter_menu_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu-images'),
        ),
    ]
